/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.dto.ad;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Images reference of an organisation */
@org.apache.avro.specific.AvroGenerated
public class OrgImage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3599758944770181591L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrgImage\",\"namespace\":\"net.stefanfuchs.fux.avro.dto.ad\",\"doc\":\"Images reference of an organisation\",\"fields\":[{\"name\":\"reference\",\"type\":[\"null\",\"string\"],\"doc\":\"path to the image\",\"default\":null},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"doc\":\"Description of the image\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrgImage> ENCODER =
      new BinaryMessageEncoder<OrgImage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrgImage> DECODER =
      new BinaryMessageDecoder<OrgImage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrgImage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrgImage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrgImage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrgImage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrgImage from a ByteBuffer. */
  public static OrgImage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** path to the image */
  @Deprecated public java.lang.CharSequence reference;
  /** Description of the image */
  @Deprecated public java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrgImage() {}

  /**
   * All-args constructor.
   * @param reference path to the image
   * @param description Description of the image
   */
  public OrgImage(java.lang.CharSequence reference, java.lang.CharSequence description) {
    this.reference = reference;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return reference;
    case 1: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: reference = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'reference' field.
   * @return path to the image
   */
  public java.lang.CharSequence getReference() {
    return reference;
  }

  /**
   * Sets the value of the 'reference' field.
   * path to the image
   * @param value the value to set.
   */
  public void setReference(java.lang.CharSequence value) {
    this.reference = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return Description of the image
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * Description of the image
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Creates a new OrgImage RecordBuilder.
   * @return A new OrgImage RecordBuilder
   */
  public static net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder newBuilder() {
    return new net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder();
  }

  /**
   * Creates a new OrgImage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrgImage RecordBuilder
   */
  public static net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder newBuilder(net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder other) {
    return new net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder(other);
  }

  /**
   * Creates a new OrgImage RecordBuilder by copying an existing OrgImage instance.
   * @param other The existing instance to copy.
   * @return A new OrgImage RecordBuilder
   */
  public static net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder newBuilder(net.stefanfuchs.fux.avro.dto.ad.OrgImage other) {
    return new net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder(other);
  }

  /**
   * RecordBuilder for OrgImage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrgImage>
    implements org.apache.avro.data.RecordBuilder<OrgImage> {

    /** path to the image */
    private java.lang.CharSequence reference;
    /** Description of the image */
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.reference)) {
        this.reference = data().deepCopy(fields()[0].schema(), other.reference);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrgImage instance
     * @param other The existing instance to copy.
     */
    private Builder(net.stefanfuchs.fux.avro.dto.ad.OrgImage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.reference)) {
        this.reference = data().deepCopy(fields()[0].schema(), other.reference);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'reference' field.
      * path to the image
      * @return The value.
      */
    public java.lang.CharSequence getReference() {
      return reference;
    }

    /**
      * Sets the value of the 'reference' field.
      * path to the image
      * @param value The value of 'reference'.
      * @return This builder.
      */
    public net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder setReference(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.reference = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'reference' field has been set.
      * path to the image
      * @return True if the 'reference' field has been set, false otherwise.
      */
    public boolean hasReference() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'reference' field.
      * path to the image
      * @return This builder.
      */
    public net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder clearReference() {
      reference = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * Description of the image
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }

    /**
      * Sets the value of the 'description' field.
      * Description of the image
      * @param value The value of 'description'.
      * @return This builder.
      */
    public net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * Description of the image
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'description' field.
      * Description of the image
      * @return This builder.
      */
    public net.stefanfuchs.fux.avro.dto.ad.OrgImage.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrgImage build() {
      try {
        OrgImage record = new OrgImage();
        record.reference = fieldSetFlags()[0] ? this.reference : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrgImage>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrgImage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrgImage>
    READER$ = (org.apache.avro.io.DatumReader<OrgImage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
