/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.common;
@SuppressWarnings("all")
/** List of possible types of pages */
@org.apache.avro.specific.AvroGenerated
public enum PageType {
  LANDING_PAGE, SEARCH_RESULT, START_PAGE, USER_PROFILE, COMPANY_PROFILE, AD_DETAIL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PageType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.common\",\"doc\":\"List of possible types of pages\",\"symbols\":[\"LANDING_PAGE\",\"SEARCH_RESULT\",\"START_PAGE\",\"USER_PROFILE\",\"COMPANY_PROFILE\",\"AD_DETAIL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
