/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.common;
@SuppressWarnings("all")
/** List of possible sources (devices) */
@org.apache.avro.specific.AvroGenerated
public enum SourceType {
  UNKNOWN, DESKTOP, MOBILE_BROWSER, IOS, ANDROID, API  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SourceType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.common\",\"doc\":\"List of possible sources (devices)\",\"symbols\":[\"UNKNOWN\",\"DESKTOP\",\"MOBILE_BROWSER\",\"IOS\",\"ANDROID\",\"API\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
