/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.common;
@SuppressWarnings("all")
/** List of possible verticals */
@org.apache.avro.specific.AvroGenerated
public enum VerticalType {
  MARKETPLACE, ESTATE, MOTOR, UNDEFINED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VerticalType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.common\",\"doc\":\"List of possible verticals\",\"symbols\":[\"MARKETPLACE\",\"ESTATE\",\"MOTOR\",\"UNDEFINED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
