/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.ad;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AdEventType {
  AD_VIEWED, SELLER_CALLED, AD_CREATED, AD_PUBLISHED, UPSELLING_BOUGHT, SEND_TO_AD_CONTROL, AD_RECOMMENDED, AD_UNPUBLISHED, SELLER_CONTACTED, AD_DELETED, AD_REJECTED, AD_APPROVED, AD_PENDING_FOR_PAYMENT, AD_EXPIRED, AD_DEACTIVATED, AD_ACTIVATED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AdEventType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.ad\",\"symbols\":[\"AD_VIEWED\",\"SELLER_CALLED\",\"AD_CREATED\",\"AD_PUBLISHED\",\"UPSELLING_BOUGHT\",\"SEND_TO_AD_CONTROL\",\"AD_RECOMMENDED\",\"AD_UNPUBLISHED\",\"SELLER_CONTACTED\",\"AD_DELETED\",\"AD_REJECTED\",\"AD_APPROVED\",\"AD_PENDING_FOR_PAYMENT\",\"AD_EXPIRED\",\"AD_DEACTIVATED\",\"AD_ACTIVATED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
