/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.ad;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum AdType {
  CONSUMER_GOOD, ESTATE_BUY, ESTATE_RENT, CAR, MOTOR_CYCLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AdType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.ad\",\"symbols\":[\"CONSUMER_GOOD\",\"ESTATE_BUY\",\"ESTATE_RENT\",\"CAR\",\"MOTOR_CYCLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
