/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.ad;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum DisplayStatus {
  ACTIVE, SOLD, RESERVED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DisplayStatus\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.ad\",\"symbols\":[\"ACTIVE\",\"SOLD\",\"RESERVED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
