/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.ad;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Status {
  UNKNOWN, ACTIVE, DELETED, EXPIRED, INACTIVE, NEW, EDITING, PENDING_FOR_APPROVAL, PENDING_FOR_PAYMENT, REJECTED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.ad\",\"symbols\":[\"UNKNOWN\",\"ACTIVE\",\"DELETED\",\"EXPIRED\",\"INACTIVE\",\"NEW\",\"EDITING\",\"PENDING_FOR_APPROVAL\",\"PENDING_FOR_PAYMENT\",\"REJECTED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
