/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.user;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UserEventType {
  USER_LOGGED_IN, USER_PASSWORD_CHANGED, NEWSLETTER_SUBSCRIBED, NEWSLETTER_UNSUBSCRIBED, USER_REGISTERED, USER_PROFILE_CHANGED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserEventType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.user\",\"symbols\":[\"USER_LOGGED_IN\",\"USER_PASSWORD_CHANGED\",\"NEWSLETTER_SUBSCRIBED\",\"NEWSLETTER_UNSUBSCRIBED\",\"USER_REGISTERED\",\"USER_PROFILE_CHANGED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
