/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package net.stefanfuchs.fux.avro.enums.entity.organisation;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OrganisationEventType {
  ORGANISATION_PROFILE_VIEWED, ORGANISATION_REGISTERED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrganisationEventType\",\"namespace\":\"net.stefanfuchs.fux.avro.enums.entity.organisation\",\"symbols\":[\"ORGANISATION_PROFILE_VIEWED\",\"ORGANISATION_REGISTERED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
